# Config for A SkyBlock (also playable as AcidIsland)
general:
   # Sea level height (don't changes this mid-game unless you delete the world)
   # Minimum is 0, which means you are playing sky block!
   # If sea level is less than about 10, then players will drop right through it
   # if it exists. Makes for an interesting variation on sky block.
   sealevel: 0

   # Island level - the height of the island.
   # Height should not be lower than sea level, but can be if you have an
   # island schematic that supports it
   # Lowest level is 5
   islandlevel: 120

   # Name of the world - if it does not exist then it will be generated
   worldName: ASkyBlock

   # Use the control panel as the default display for /island
   # /island will always create an island if one does not exist
   # If the control panel is not used, then /island will teleport the player home
   usecontrolpanel: false

   # Create Nether - if this is false, the nether world will not be made and access to
   # AcidIsland control of the nether will not occur. Other plugins may still enable
   # portal usage.
   # Note: Some challenges will not be possible if there is no nether.
   # Note that in AcidIsland, all players arrive at the same portal and entering a
   # portal will return them back to their islands.
   createnether: true

   # Schematics
   # The default schematic file (if used) for all players is island.schematic.
   # To give players other schematics, list a permission and the filename
   # then give the player that permission (it can be anything)
   # If the file does not exist, it will not load.
   schematics:
     schematic.vip: vipisland.schematic
     schematic.vip2: vip2island.schematic
     schematic.jail: jail.schematic 

   #How long a player must wait before they can reset their island again
   resetwait: 300

   #How many resets a player is allowed (override with /asadmin clearreset <player>
   #Value of -1 means unlimited, 0 means hardcore - no resets.
   #Example, 2 resets means they get 2 resets or 3 islands lifetime
   resetlimit: 2

   #Commands to run when the player resets their island (uncomment and customize)
   # [player] is the player name of who is reseting
   #resetcommands:
   #  - kit tools [player]
   #  - some other command

   # Ops receive damage from acid (Set to true if you want Ops to play properly)
   damageops: false

   # Acid damage to player per second by being in acid if they have no armor on.
   # A fully health player has 20 health points. Players will regen some health
   # so the default will give players about 3 seconds to get out the acid
   # 0 = no damage, 10 = default damage, 20 = instant death
   aciddamage: 0
   # Damage that monsters will experience.
   mobaciddamage: 0
   # Damage that rain does.
   raindamage: 0
   # Damage that animals will experience in acid.
   animaldamage: 0
   # Damage chickens in acid - true or false - chickens tend to go swimming...
   damagechickens: false

   # Damage type to apply in addition to acid damage
   # Types can be : SLOW, SLOW_DIGGING, CONFUSION,BLINDNESS, HUNGER, WEAKNESS and POISON
   # If you just want these to act, then make the acid damage 0 above
   # Note - these are potion effects and so can be cured by milk
   damagetype:

   # Removing mobs - this kills all monsters in the vicinity. Benefit is that it helps
   # players return to their island if the island has been overrun by monsters
   # Con is that it kills any mob grinders 
   # Remove mobs when logging in
   loginremovemobs: true

   # Remove mobs when /island
   islandremovemobs: false

   # Sets the limit for number of monsters that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   monsterspawnlimit: 70

   #[integer] Sets the limit for number of animals that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   animalspawnlimit: 15

   # Breeding limits - if this is set to more than 0, then players will not be able
   # to breed more animals than that number on their island. A value of zero means no
   # limit. Note that animals will not be killed or reduced to this limit.
   # This will not affect mobspawn blocks or monster egg use. Note that hearts will
   # still appear, but breeding will not happen.
   breedinglimit: 0

   #[integer] Sets the limit for number of water animals [squid] that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   wateranimalspawnlimit: 15

   #[integer] Island below this level will be removed if they are abandoned and admins issue the purge command
   abandonedislandlevel: 10


   ##### Economy ######
   # Use economy or not. If true, an economy plugin is required. If false, no money
   # is used or given. The mini-shop is disabled.
   useeconomy: true

   # Reset Money - if this is true, will reset the player's money to
   # the starting money (see below) when they start an island or reset
   # Recommendation is that this is set to true, but if you run multi-worlds
   # make sure your economy handles multi-worlds too.
   resetmoney: false

   # Starting money - this is how much money new players will have as their
   # balance at the start of an island. 
   startingmoney: 10.00

   # Reset Challenges - if this is true, player's challenges will reset when they
   # reset an island
   resetchallenges: true

   # Reset inventory - if true, the player's inventory will be cleared when they start
   # or restart and island. Default is true.
   # Note: if you have MultiInv running or a similar inventory control plugin, that
   # plugin may still reset the inventory when the world changes.
   resetinventory: true

   # Nether spawn protection radius - this is the distance around the nether spawn
   # that will be protected from player interaction (breaking blocks, pouring lava etc.)
   # Minimum is 0 (not recommended), maximum is 100. Default is 25.
   # Only applies to standard nether.
   netherspawnradius: 25

   # Broadcast 1st time challenge completion messages to all players.
   # Change to false if the spam becomes too much.
   broadcastmessages: true

   # Allow /island teleport when falling. If set to false, all teleporting is
   # disabled until death from the void or until you hit something.
   allowfallingteleport: true

   # Remove non-repeatable challenges from the challenge GUI when complete
   removecompleteonetimechallenges: false

   # Add enchanted glow to completed challenges (does not work with all clients)
   # Also currently adds an "enchanted" line of text...
   addcompletedglow: true

##### Island Related Settings #####

island:
   # Space between islands in blocks - never change this mid-game.
   distance: 150

   # The size of the protective region for each island. Must be at least 16 blocks
   # less than the island distance.
   # If you want to override this change overridelimit to true. This may result in
   # incomplete island deletion (~15% of the time if the island goes to edges)
   protectionRange: 100
   overridelimit: false

   # Coordinate offset - never change this mid-game and there is no
   # need to set this. It is for compatibility with IslandWorld maps and set by
   # BlockConverter.
   xoffset: 0
   zoffset: 0

   # Max team size
   maxteamsize: 4
   # VIP team size - set by permission askyblock.team.vip
   vipteamsize: 8
   # VIP2 team size - set by permission askyblock.team.vip2
   vip2teamsize: 12

   # Items that will be in the chest when the player starts an island
   # Must be in Bukkit Materials format. Format is <Material>:<Qty>
   # or <Material>:<Damage>:<Qty>
   # Use <Damage> to set the durability of a item or to select sub-items/colors.
   # Format for POTION is POTION:<effect>:<qty> or POTION:<effect>:<type>:<qty>
   # <type> is EXTENDED, SPLASH or EXTENDEDSPLASH. Not all potions can be extended.
   # Check console for errors and guidance after reloading configuration
   # Set to '' if items are included in the schematic
   chestItems: 'ICE:2 MELON:1 TORCH:2 BONE:1 LAVA_BUCKET:1 PUMPKIN_SEEDS:1 SUGAR_CANE:1 RED_MUSHROOM:1 BROWN_MUSHROOM:1 CACTUS:1 BREAD:1 WHEAT:1 LEATHER_BOOTS:1 LEATHER_HELMET:1 LEATHER_CHESTPLATE:1 LEATHER_LEGGINGS:1'

   # Island Protection Settings
   # PVP is allowed or not.
   # If PVP is denied, then players can expel other players from islands
   # otherwise players have to kill each other
   allowPvP: false
   # Other players can break blocks or not or generally damage things
   allowbreakblocks: false
   # Other players can place blocks
   allowplaceblocks: false
   # Allow players to be able to sleep in beds not on their island
   allowbeduse: false
   # Allow players to use buckets, either fill or dump them
   allowbucketuse: false
   # Allow players to shear sheep
   allowshearing: false
   # Allow players to throw enderpearls and teleport
   allowenderpearls: false
   # Allow players to use doors or trapdoors. If a door is operated by a button or redstone, this does not count
   allowdooruse: false
   # Allow players to use levers or buttons
   allowleverbuttonuse: false
   # Allow players to trample crops
   allowcroptrample: false
   # Allow players to access chests of any kind, droppers, dispensers and hoppers
   allowchestaccess: false
   # Allow players to access furnaces
   allowfurnaceuse: false
   # Allow players to adjust diodes or comparators
   allowredstone: false
   # Allow players to use jukeboxes, eject discs and hit note blocks
   allowmusic: false
   # Allow players to use crafting benches
   allowcrafting: true
   # Allow players to use cauldrons and brewing stands
   allowbrewing: false
   # Allow gates to be used
   allowgateuse: false
   # Allow friendly mobs to be hurt (cows etc.)
   allowhurtmobs: false
   # Allow monsters to be hurt (creepers,slimes, etc.)
   # Don't change this to false unless you accept that island visitors will not be
   # able to defend themselves!
   allowhurtmonsters: true
   # Allow Enderman Griefing (default is to allow, see next setting)
   allowendermangriefing: true
   # Make enderman drop the block he is holding if he dies (recommended)
   endermandeathdrop: true
   # Allow creeper explosion damage to block (explosion still hurts)
   allowcreeperdamage: true
   # Allow TNT damage to blocks (stops players using TNT to destroy other's islands)
   allowtntdamage: false
   # Allow spawn egg use
   allowspawneggs: false
   # Allow animal breeding by visitors
   allowbreeding: false
   # Allow use of Flint & Steel by visitors
   allowfire: false
   # Allow chests to be blown up by creepers or TNT
   allowchestdamage: false
   # Allow leash use
   allowleashuse: false
   # Allow use of enchanting tables
   allowenchanting: true
   # Allow anvil use by visitors
   allowanviluse: true
   # Allow item drop by visitors
   allowvisitoritemdrop: true
   # Allow item pickup by visitors
   allowvisitoritempickup: true
   # Allow visitors to keep their items if they die
   allowvisitorkeepinvondeath: false

# This section contains the biomes that can be bought or used
biomesettings:
  # The default cost for changing biome. Can be over-ridden by the Biome settings
  # Default is 100 if this is not set. Cannot be <0.
  defaultcost: 100

  # Default biome - what every player will start with. Default is PLAINS. See below
  # for other options
  defaultbiome: PLAINS

# List of biomes and their settings.
# Cost - cost in currency to change to that biome
# permission - the permission required to use that biome
# If the biome is not listed, it is not available
# icon = icon used in control panel
# friendlyname = A friendly name for the biome. If it does not exist, the official
# biome name will be used with pretty formatting. Mostly this is just used to convert
# Hell to Nether
# description = a description of the biome and what it gives the player
# remove ice/water/snow - will be done once when the biome is made

biomes:
  COLD_TAIGA:
    icon: SAPLING
    description: Snowy and cold. Brrr.
  DESERT:
    icon: DEAD_BUSH
    description: A dry desert. Warning - Ice or snow have to go.
  FLOWER_FOREST:
    icon: RED_ROSE
    description: The place for flowers!
  HELL:
    icon: LAVA_BUCKET
    cost: 1000
    permission: askyblock.biomes.hell
    friendlyname: Nether
    description: Warning - all water, snow and ice will be removed.
  JUNGLE:
    icon: VINE
    description: Lush jungle. Warning - Ice or snow have to go.
  MUSHROOM_ISLAND:
    icon: RED_MUSHROOM
    permission: askyblock.biomes.mushoom_island
    description: Mushroom island
  PLAINS:
    icon: GRASS
    description: Plain plains!
    cost: 0
  SWAMPLAND:
    icon: WATER_LILY
    description: Swampy. Warning - Ice or snow have to go.
  MESA:
    icon: HARD_CLAY
    description: Rare dry, desert biome. Warning - Ice or snow have to go.
    cost: 500
  SAVANNA:
    icon: LONG_GRASS
    description: Flat and dry, no rain. Warning - Ice or snow have to go.
  ROOFED_FOREST:
    icon: LOG
    description: Black forest
