#############################################################################
# Config for A SkyBlock (also playable as AcidIsland)
# For initial set up you must configure or check at least these settings:
#
# 1. islandLevel - the height you want your islands to float
# 2. resetmoney - set to true so that everyone starts with nothing
# 3. distance (in the island section) - the distance between islands
# 4. protectionRange - big a player's island is at the start
#
# The plugin will NOT start until #3 is set!!!
#############################################################################

general:

   # Check for updates - this will tell Ops and the console if there is a new
   # version available. It contacts dev.bukkit.org to request the latest version
   # info. It does not download the latest version or change any files
   checkupdates: true

   # Sea level height (don't changes this mid-game unless you delete the world)
   # Minimum is 0, which means you are playing sky block!
   # If sea level is less than about 10, then players will drop right through it
   # if it exists. Makes for an interesting variation on sky block.
   sealevel: 0

   # Island level - the height of the island.
   # Height should not be lower than sea level, but can be if you have an
   # island schematic that supports it
   # Lowest level is 5
   islandlevel: 120

   # Name of the world - if it does not exist then it will be generated
   worldName: ASkyBlock

   # Use the control panel as the default display for /island
   # /island will always create an island if one does not exist
   # If the control panel is not used, then /island will teleport the player home
   usecontrolpanel: false

   # Create Nether - if this is false, the nether world will not be made and access to
   # AcidIsland control of the nether will not occur. Other plugins may still enable
   # portal usage.
   # Note: Some challenges will not be possible if there is no nether.
   # Note that in AcidIsland, all players arrive at the same portal and entering a
   # portal will return them back to their islands.
   createnether: true

   # Try new island-style nether. Change to true
   # Still in Beta!
   newnether: false

   # Schematics
   # The default schematic file (if used) for all players is island.schematic.
   # To give players other schematics, list a permission and the filename
   # then give the player that permission (it can be anything)
   # If the file does not exist, it will not load.

   schematics:
   #  Note that in this example, the permission is 'schematic.vip'. It can be anything
   #  you like. For example, an existing permission for a rank of player.
   # Uncomment the lines after this one after you change them...
   #  schematic.vip: vipisland.schematic
   #  schematic.vip2: vip2island.schematic
   #  schematic.jail: jail.schematic 

   #How long a player must wait before they can reset their island again in second
   resetwait: 300

   #The number of seconds to wait for confirmation of a reset
   resetconfirmwait: 10

   #How long a player must wait until they can rejoin a team island after being
   #kicked in minutes. This slows the effectiveness of players repeating challenges
   #by repetitively being invited to a team island.
   invitewait: 60

   # Island level calculation cool down in seconds
   levelwait: 60

   #How many resets a player is allowed (override with /asadmin clearreset <player>
   #Value of -1 means unlimited, 0 means hardcore - no resets.
   #Example, 2 resets means they get 2 resets or 3 islands lifetime
   resetlimit: 2

   #Commands to run when the player resets their island (uncomment and customize)
   # [player] is the player name of who is reseting
   resetcommands:
   #- kit tools [player]
   #- some other command

   # Commands to execute when player leaves a team, either by leaving or being kicked
   # Commands will execute even if the player is offline, so may cause errors in
   # the console if the commands doesn't make sense
   leavecommands:
   #- kit tools [player]

   # Ops receive damage from acid (Set to true if you want Ops to play properly)
   damageops: false

   # Acid damage to player per second by being in acid if they have no armor on.
   # A fully health player has 20 health points. Players will regen some health
   # so the default will give players about 3 seconds to get out the acid
   # 0 = no damage, 10 = default damage, 20 = instant death
   aciddamage: 0
   # Damage that monsters will experience.
   mobaciddamage: 0
   # Damage that rain does.
   raindamage: 0
   # Damage that animals will experience in acid.
   animaldamage: 0
   # Damage chickens in acid - true or false - chickens tend to go swimming...
   damagechickens: false

   # Damage type to apply in addition to acid damage
   # Types can be : SLOW, SLOW_DIGGING, CONFUSION,BLINDNESS, HUNGER, WEAKNESS and POISON
   # If you just want these to act, then make the acid damage 0 above
   # Note - these are potion effects and so can be cured by milk
   damagetype:

   # Removing mobs - this kills all monsters in the vicinity. Benefit is that it helps
   # players return to their island if the island has been overrun by monsters
   # Con is that it kills any mob grinders 
   # Remove mobs when logging in
   loginremovemobs: true

   # Remove mobs when /island
   islandremovemobs: false

   # Sets the limit for number of monsters that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   monsterspawnlimit: 70

   #[integer] Sets the limit for number of animals that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   animalspawnlimit: 15

   # Breeding limits - if this is set to more than 0, then players will not be able
   # to breed more animals than that number on their island. A value of zero means no
   # limit. Note that animals will not be killed or reduced to this limit.
   # This WILL affect mobspawn blocks AND monster egg use. Note that hearts will
   # still appear, but breeding will not happen.
   breedinglimit: 0

   #[integer] Sets the limit for number of water animals [squid] that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   wateranimalspawnlimit: 15

   #[integer] Island below this level will be removed if they are abandoned and admins issue the purge command
   abandonedislandlevel: 10


   ##### Economy ######
   # Use economy or not. If true, an economy plugin is required. If false,
   # no money is used or give and the mini-shop is disabled.
   # If there is no economy plugin present anyway, money will be automatically
   # disabled.
   useeconomy: true

   # Reset Money - if this is true, will reset the player's money to
   # the starting money (see below) when they start an island or reset
   # Recommendation is that this is set to true, but if you run multi-worlds
   # make sure your economy handles multi-worlds too.
   resetmoney: false

   # Starting money - this is how much money new players will have as their
   # balance at the start of an island. 
   startingmoney: 10.00

   # Reset Challenges - if this is true, player's challenges will reset when they
   # reset an island
   resetchallenges: true

   # Reset inventory - if true, the player's inventory will be cleared when they start
   # or restart and island. Default is true.
   # Note: if you have MultiInv running or a similar inventory control plugin, that
   # plugin may still reset the inventory when the world changes.
   resetinventory: true

   # Reset Ender Chest - if true, the player's Ender Chest will be cleared when they
   # start or restart their island. Default is false.
   # NOTE: Ender Chests spawn worlds, so it will clear ALL chests. In general,
   # Enderchests should not be allowed in ASkyblock unless you only run the ASkyblock
   # world. Ender Chest crafting and use is governed by the askyblock.craft.enderchest
   # permission.
   resetenderchest: false

   # Nether spawn protection radius - this is the distance around the nether spawn
   # that will be protected from player interaction (breaking blocks, pouring lava etc.)
   # Minimum is 0 (not recommended), maximum is 100. Default is 25.
   # Only applies to standard nether.
   netherspawnradius: 25

   # Broadcast 1st time challenge completion messages to all players.
   # Change to false if the spam becomes too much.
   broadcastmessages: true

   # Allow /island teleport when falling. If set to false, all teleporting is
   # disabled until death from the void or until you hit something.
   # See commands that this will block too
   allowfallingteleport: true
   blockingcommands:
   - home
   #- anotherCommand
   #- andAnotherOne

   # Remove non-repeatable challenges from the challenge GUI when complete
   removecompleteonetimechallenges: false

   # Add enchanted glow to completed challenges (does not work with all clients)
   # Also currently adds an "enchanted" line of text...
   addcompletedglow: true

   # Use physics when pasting schematic blocks. If this is false, then blocks
   # like water will not flow from the schematic
   usephysics: false
   
   # Calculate level on login
   # If true, the plugin will run the level command for the player when they login
   # If the command is busy, it will fail silently
   loginlevel: false

   # Maximum number of homes a player can have
   # Accessed via sethome <number> or go <number>
   maxhomes: 1

   # Make island if player teleports to the island world and does not have one
   makeislandifnone: false

   # Immediately teleport player to their island (home 1 if it exists) when 
   # entering the world
   immediateteleport: false

   # Set TEAMSUFFIX variable to player's island level
   # If true, this will set the server TEAMNAME variable to the player's name and
   # TEAMSUFFIX to the player's island level.
   # Use in chat. e.g., for essentials chat, the format could be:
   #   format: '<{DISPLAYNAME}> (Level {TEAMSUFFIX}): {MESSAGE}'
   # <tastybento> (Level: 223): hi there
   # If you have other plugins that use scoreboards/teams, this may mess with them
   setteamsuffix: false

##### Island Related Settings #####

island:
   # Space between islands in blocks - NEVER change this mid-game.
   # Values for a new world:
   # 400 - puts players distance enough that they usually cannot see each other
   # 200 - allows some expansion of the protected zone (recommended)
   # 110 - for compatibility with established worlds. Cozy.
   # 50 - minimum - not recommended
   # IF YOU ARE UPGRADING YOU MUST USE YOUR OLD VALUE EXACTLY, E.G., 110
   #
   # You MUST change this value to something to start the plugin!

   distance: -1

   # The size of the protective region for new islands. Must be at least 16 blocks
   # less than the island distance. Large sizes will slow down island level calculation
   # when players do /is level.
   #
   # Recommended size is 100 because it gives players a good starting size.
   # Minimum size is 50.
   # Admins can change protection sizes for players individually using 

   protectionRange: 100

   # If you want to try to have protection range = distance set the following to true.
   # It may result is incomplete deletion of islands. Not recommended.
   overridelimit: false

   # Start islands at these coordinates. This is where new islands will start in the
   # world. These must be a factor of your island distance, but the plugin will auto
   # calculate the closest location on the grid. Islands develop around this location
   # both positively and negatively in a square grid.
   # If none of this makes sense, leave at 0,0.
   startx: 0
   startz: 0

   # Coordinate offset - never change this mid-game and there is no
   # need to set this. It is for compatibility with IslandWorld maps and set by
   # BlockConverter.
   xoffset: 0
   zoffset: 0

   # Max team size
   maxteamsize: 4
   # VIP team size - set by permission askyblock.team.vip
   vipteamsize: 8
   # VIP2 team size - set by permission askyblock.team.vip2
   vip2teamsize: 12

   # Items that will be in the chest when the player starts an island
   # Must be in Bukkit Materials format. Format is <Material>:<Qty>
   # or <Material>:<Damage>:<Qty>
   # Use <Damage> to set the durability of a item or to select sub-items/colors.
   # Format for POTION is POTION:<effect>:<qty> or POTION:<effect>:<type>:<qty>
   # <type> is EXTENDED, SPLASH or EXTENDEDSPLASH. Not all potions can be extended.
   # Check console for errors and guidance after reloading configuration
   # Set to '' if items are included in the schematic

   chestItems: 'ICE:2 MELON:1 TORCH:2 BONE:1 LAVA_BUCKET:1 PUMPKIN_SEEDS:1 SUGAR_CANE:1 RED_MUSHROOM:1 BROWN_MUSHROOM:1 CACTUS:1 BREAD:1 WHEAT:1 LEATHER_BOOTS:1 LEATHER_HELMET:1 LEATHER_CHESTPLATE:1 LEATHER_LEGGINGS:1'

   # Your island companion
   # Options are: COW, PIG, SHEEP, CHICKEN, VILLAGER, HORSE, IRON_GOLEM, OCELOT,
   # RABBIT, WOLF or NOTHING. Default is COW.

   companion: COW
   # This is a list of names, picked at random that will apply to the companion
   # You can add more if you like. If none are listed, the companion will not be
   # named.
   companionnames:
   - "&9[player]'s cow"
   - "&cEmergency &fFood?"
   - "&aD&6a&di&6s&9y"

   # Island Protection Settings

   # PVP is allowed or not.
   allowPvP: false
   allowNetherPvP: false
   # Other players can break blocks or not or generally damage things
   allowbreakblocks: false
   # Other players can place blocks
   allowplaceblocks: false
   # Allow players to be able to sleep in beds not on their island
   allowbeduse: false
   # Allow players to use buckets, either fill or dump them
   allowbucketuse: false
   # Allow players to shear sheep
   allowshearing: false
   # Allow players to throw enderpearls and teleport
   allowenderpearls: false
   # Allow players to use doors or trapdoors. If a door is operated by a button or redstone, this does not count
   allowdooruse: false
   # Allow players to use levers or buttons
   allowleverbuttonuse: false
   # Allow players to trample crops
   allowcroptrample: false
   # Allow players to access chests of any kind, droppers, dispensers and hoppers
   allowchestaccess: false
   # Allow players to access furnaces
   allowfurnaceuse: false
   # Allow players to adjust diodes or comparators
   allowredstone: false
   # Allow players to use jukeboxes, eject discs and hit note blocks
   allowmusic: false
   # Allow players to use crafting benches
   allowcrafting: true
   # Allow players to use cauldrons and brewing stands
   allowbrewing: false
   # Allow gates to be used
   allowgateuse: false
   # Allow friendly mobs to be hurt (cows etc.)
   allowhurtmobs: false
   # Allow monsters to be hurt (creepers,slimes, etc.)
   # Don't change this to false unless you accept that island visitors will not be
   # able to defend themselves!
   allowhurtmonsters: true
   # Allow Enderman Griefing (default is to allow, see next setting)
   allowendermangriefing: true
   # Make enderman drop the block he is holding if he dies (recommended)
   endermandeathdrop: true
   # Allow creeper explosion damage to block (explosion still hurts)
   allowcreeperdamage: true
   # Allow TNT damage to blocks (stops players using TNT to destroy other's islands)
   allowtntdamage: false
   # Allow spawn egg use
   allowspawneggs: true
   # Allow animal breeding by visitors
   allowbreeding: false
   # Allow use of Flint & Steel by visitors
   allowfire: false
   # Allow chests to be blown up by creepers or TNT
   allowchestdamage: false
   # Allow leash use
   allowleashuse: false
   # Allow use of enchanting tables
   allowenchanting: true
   # Allow anvil use by visitors
   allowanviluse: true
   # Allow item drop by visitors
   allowvisitoritemdrop: true
   # Allow item pickup by visitors
   allowvisitoritempickup: true
   # Allow visitors to keep their items if they die
   allowvisitorkeepinvondeath: false
   # Allow armor stand use by visitors
   allowarmorstanduse: false
   # Allow beacon use by visitors
   allowbeaconaccess: false
   # Allow portal use by visitors
   allowportaluse: true

# Spawn protection options - different to regular islands
spawn:
  # The following are recommended to be true at spawn
  allowdooruse: true
  allowleverbuttonuse: true
  allowchestaccess: true
  allowfurnaceuse: true
  allowmusic: true
  allowcrafting: true
  allowbrewing: true
  allowgateuse: true
  allowanimalspawn: true
  allowmobkilling: true
  allowenchanting: true
  allowanviluse: true

  # The following are recommended to be false at spawn, but you can change
  allowbreakblocks: false
  allowplaceblocks: false
  allowredstone: false
  allowanimalkilling: false
  allowmobspawn: false
  allowbeaconaccess: false
  allowspawneggs: false
  alloweggs: false
  # The following stops water above sea level from being acid at spawn if acid is active
  allowspawnnoacidwater: false

# This section contains the biomes that can be bought or used
biomesettings:
  # The default cost for changing biome. Can be over-ridden by the Biome settings
  # Default is 100 if this is not set. Cannot be <0.
  defaultcost: 100

  # Default biome - what every player will start with. Default is PLAINS. See below
  # for other options
  defaultbiome: PLAINS

# List of biomes and their settings.
# Cost - cost in currency to change to that biome
# permission - the permission required to use that biome
# If the biome is not listed, it is not available
# icon = icon used in control panel
# friendlyname = A friendly name for the biome. If it does not exist, the official
# biome name will be used with pretty formatting. Mostly this is just used to convert
# Hell to Nether
# description = a description of the biome and what it gives the player
# remove ice/water/snow - will be done once when the biome is made

biomes:
  COLD_TAIGA:
    icon: SAPLING
    description: Snowy and cold. Brrr.
  DESERT:
    icon: DEAD_BUSH
    description: A dry desert. Warning - Ice or snow have to go.
  FLOWER_FOREST:
    icon: RED_ROSE
    description: The place for flowers!
  HELL:
    icon: LAVA_BUCKET
    cost: 1000
    # Note, this permission can be anything you like
    permission: askyblock.biomes.hell
    friendlyname: Nether
    description: Warning - all water, snow and ice will be removed.
  JUNGLE:
    icon: VINE
    description: Lush jungle. Warning - Ice or snow have to go.
  MUSHROOM_ISLAND:
    icon: RED_MUSHROOM
    # Note, this permission can be anything you like
    permission: askyblock.biomes.mushoom_island
    description: Mushroom island
  PLAINS:
    icon: GRASS
    description: Plain plains!
    cost: 0
  SWAMPLAND:
    icon: WATER_LILY
    description: Swampy. Warning - Ice or snow have to go.
  MESA:
    icon: HARD_CLAY
    description: Rare dry, desert biome. Warning - Ice or snow have to go.
    cost: 500
  SAVANNA:
    icon: LONG_GRASS
    description: Flat and dry, no rain. Warning - Ice or snow have to go.
  ROOFED_FOREST:
    icon: LOG
    description: Black forest
